version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
    - "6379:6379"
    command:
    - --loglevel warning
    volumes:
    - redis-volume:/data:Z

  postgres:
    image: postgres:10
    ports:
    - "5432:5432"
    volumes:
    - ${POSTGRES_VOLUME:-postgres-volume}:/var/lib/postgresql/data:Z
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}

  app:
    image: docker.pkg.github.com/marquicus/${PROJECT}
    command: sh -c "/sbin/wait-for-it postgres:5432 -t 60 -- echo 'Database is up' && alembic -c alembic.ini revision --autogenerate -m 'init' && alembic -c development.ini upgrade head && initialize_travelcrm_db production.ini && pserve production.ini"
    depends_on:
    - redis
    - postgres
    links:
    - postgres
    ports:
    - "6543:6543"
    volumes:
    - /logs:/logs:Z
    environment:
    - REDIS_HOST=redis
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - SENTRY_DSN=${SENTRY_DSN}
    - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
    - SECRET_KEY=${SECRET_KEY}

volumes:
  redis-volume:
  postgres-volume:
